server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Yvaine2251/SpringCloud.git
          searchPaths: config
          username: Yvaine2251
          password: a3879080
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka